# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./eventease-app  # Replace with your actual project directory

      - name: Build solution
        run: dotnet build --no-restore --configuration Release
        working-directory: ./eventease-app  # Replace with your actual project directory

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        working-directory: ./eventease-app  # Replace with your actual project directory
