# .github/workflows/dotnet.yml
name: .NET CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore Web App dependencies
        run: dotnet restore ./eventease-app/eventease-app/eventease-app.csproj

      - name: Restore Test project dependencies
        run: dotnet restore ./eventease-app/EventEaseApp.Tests/EventEaseApp.Tests.csproj

      - name: Build Web App
        run: dotnet build --no-restore --configuration Release ./eventease-app/eventease-app/eventease-app.csproj

      - name: Build Tests
        run: dotnet build --no-restore --configuration Release ./eventease-app/EventEaseApp.Tests/EventEaseApp.Tests.csproj

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal ./eventease-app/EventEaseApp.Tests/EventEaseApp.Tests.csproj
